name: Go CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ master ]

jobs:

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Build
      run: go build -v
    - name: Test
      run: go test -v

  go-linter:
    name: Go Linter
    runs-on: ubuntu-latest
    steps:
    - name: go1.19 linter
      uses: shoukoo/golang-pipeline/go1.19/linter@master
      with:
        GOLINT: on
        GOLINTPATH: .
        MISSPELL: off